export const SERVER_DISPATCH = 'DISPATCH_SERVER'
export const UPDATE_SERVER = 'UPDATE_SERVER'
export const DISPATCH_SUCCESS = 'SUCCESS_SERVER'
export const DISPATCH_ERROR = 'ERROR_SERVER'
export const DEFAULT = 'STATE_DEFAULT'
export const SERVER_SOCKET = 'ws://10.59.64.51:8081'
export const SERVER = 'http://localhost:4000/'
