export const SERVER_DISPATCH = 'DISPATCH_SERVER'
export const UPDATE_SERVER = 'UPDATE_SERVER'
export const DISPATCH_SUCCESS = 'SUCCESS_SERVER'
export const DISPATCH_ERROR = 'ERROR_SERVER'
export const DEFAULT = 'STATE_DEFAULT'
export const SERVER_SOCKET = 'ws://10.37.0.24:8081'
export const SERVER = '/'
